# Generated by Django 3.2.5 on 2021-10-09 18:55

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='thank_you_text',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
    ]
