# Generated by Django 3.2.5 on 2021-10-05 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('home', '0004_auto_20211005_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='price',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='productpage',
            name='sku',
            field=models.IntegerField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_cta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
    ]
