# Generated by Django 3.2.5 on 2021-10-05 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211005_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpage',
            name='name',
        ),
    ]
