# Generated by Django 3.2.5 on 2021-10-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_productpage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='sku',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
