# Generated by Django 3.2.5 on 2021-10-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211005_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productpage',
            name='sku',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
