# Generated by Django 3.2.5 on 2021-10-05 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20211005_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpage',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='sku',
        ),
    ]
