# Generated by Django 3.2.5 on 2021-10-06 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20211005_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='price',
            field=models.FloatField(default=10000),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='sku',
            field=models.IntegerField(unique=True),
        ),
    ]
