# Generated by Django 3.2.5 on 2021-10-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('home', '0015_aboutpage'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='shoppage',
        #     name='page_ptr',
        # ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ProductPage',
        ),
        migrations.DeleteModel(
            name='ShopPage',
        ),
    ]
