# Generated by Django 3.2.5 on 2021-10-08 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('home', '0016_auto_20211008_0916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutPage',
        ),
    ]
